version: "3.8"

services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./Server:/app # Mount thư mục Server vào container
      - /app/bin # Ignore thư mục bin
      - /app/obj # Ignore thư mục obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Client:/app # Mount thư mục Client vào container
      - /app/node_modules # Ignore node_modules để tránh lỗi
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Password"
      ACCEPT_EULA: "Y"
