services:
  backend:
    container_name: backend
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5004
    depends_on:
      - backend
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Password"
      ACCEPT_EULA: "Y"
